'use client'

import React from 'react';

interface AIDisclaimerProps {
  message?: string;
  className?: string;
  compact?: boolean;
}

/**
 * A component that displays a disclaimer about AI-generated content
 */
const AIDisclaimer: React.FC<AIDisclaimerProps> = ({ 
  message = "This information is generated by AI and may not be completely accurate. Please verify any important details before making decisions.", 
  className = '',
  compact = false
}) => {
  if (compact) {
    return (
      <div className={`text-xs text-gray-500 italic ${className}`}>
        <span className="font-medium">AI-generated:</span> {message}
      </div>
    );
  }
  
  return (
    <div className={`bg-blue-50 border border-blue-200 rounded-md p-3 ${className}`}>
      <div className="flex">
        <div className="flex-shrink-0">
          <svg className="h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
          </svg>
        </div>
        <div className="ml-3 flex-1">
          <p className="text-sm text-blue-700">
            <span className="font-medium">AI-generated content:</span> {message}
          </p>
        </div>
      </div>
    </div>
  );
};

export default AIDisclaimer;
